### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by RodrigoWebDev** [RodrigoWebDev/anonymous-youtube-playlist-generator#32]
The tailwind has a easy way to make the dark mode: https://tailwindcss.com/docs/dark-mode. So in the Dark Mode:
- All white texts(including those inside inputs) should be `text-slate-300`
- The general background-color should be `bg-[#18181b]`
- All inputs background-color should be `bg-transparent`
- All buttons should be the outline variant, see the `src\utils\cssClasses.js` file to reuse the classes, in case we don't have it see [the tailwind-elements docs](https://tailwind-elements.com/docs/standard/components/buttons/) to get it
- The video links(screenshot bellow), should be , `bg-transparent`, `border`, `border-solid`, `border-blue-600`
![image](https://user-images.githubusercontent.com/30677819/170849524-d66afe07-1b88-440c-8369-428f19b1a52c.png)
- The "X" inside the video link should be `fill-white`
- The same style need to be applied for the sweet alert modal, so don't forget to see [the docs](https://sweetalert2.github.io/#customClass)
- The page should have a button to activate/deactivate the dark mode. The button should be located at the bottom-right at a fixed position, so when the user scroll the page the button stay at the same position
- The button need to be  a circle with the default blue background, and a white icon
- When in "dark mode" the icon should be the [moon icon](https://fontawesome.com/search?q=moon&s=solid%2Cbrands)
- When in "light mode" the icon should be the [sun icon](https://fontawesome.com/search?q=sun&s=solid%2Cbrands)
- Save the theme state(dark or light) in the local storage, to when the user reload the page the activated theme will be the last selected

**Comment by GigiLoria5** [comment]
Hi, I am trying to add this functionality.  Can you give me more details on how you would like it? I imagined it like this

![immagine](https://user-images.githubusercontent.com/41837640/170821527-9efdae4b-d1b9-4e22-9924-69c268c0187d.png)

![immagine](https://user-images.githubusercontent.com/41837640/170821530-a83a09b9-a35a-43d9-b8e6-ffe1c668d56b.png)

**Comment by RodrigoWebDev** [comment]
Sorry for the lack of information in this issue! I'm updating the description now

**Comment by RodrigoWebDev** [comment]
@GigiLoria5 Please let me know if the description is okay, or if it's missing some information. I appreciate your interest in helping

**Comment by GigiLoria5** [comment]
> @GigiLoria5 Please let me know if the description is okay, or if it's missing some information. I appreciate your interest in helping

thanks for the update, I'll let u know if I find something not mentioned

**Comment by GigiLoria5** [comment]
Hi, I wanted to update you and ask for feedback. If I haven't misinterpreted what you thought it should all be there (I only miss the sweetAlert which is a bit annoying to change). The only things that don't convince me are perhaps the buttons, because with this style I think it doesn't read very well and also the hover no longer provides feedback to the user (you don't notice the difference). 

![immagine](https://user-images.githubusercontent.com/41837640/170891735-bd9fdd91-5ab5-4fd4-8ac0-9fd828c3f935.png)

![immagine](https://user-images.githubusercontent.com/41837640/170891739-e6b435aa-bcd1-4c58-9716-3950bfde4a30.png)

**Comment by RodrigoWebDev** [comment]
It's awesome! One last thing that I forgot is the svg trash icon inside the "Delete playlist" button, it should be red like the button

> The only things that don't convince me are perhaps the buttons, because with this style I think it doesn't read very well and also the hover no longer provides feedback to the user (you don't notice the difference).

If you want to add hover I will appreciate it. The button hover should have the same styles as in the light mode

**Comment by RodrigoWebDev** [comment]
> I only miss the sweetAlert which is a bit annoying to change

It's okay, I will open a new PR for styling the Sweet Alert
